routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(\route('platform.index'));
});

// Word requests
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['platform',]], function () {
    Route::resource('word-request', \App\Http\Controllers\Admin\WordRequestController::class)
        ->middleware(\App\Http\Middleware\Admin\HasWordRequestAccess::class);

    Route::resource('questions', \App\Http\Controllers\Admin\QuestionsController::class)
        ->middleware(\App\Http\Middleware\Admin\HasQuestionsAccess::class);

    Route::resource('corrections', \App\Http\Controllers\Admin\CorrectionController::class)
        ->middleware(\App\Http\Middleware\Admin\HasCorrectionsAccess::class);

    Route::resource('wr', \App\Http\Controllers\Admin\WRController::class)
        ->middleware(\App\Http\Middleware\Admin\HasWordRequestAccess::class);
});

resources/views/admin/body.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title', 'Панель администратора')</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    @livewireStyles
    @stack('styles')
</head>
<body>
<div class="d-flex justify-content-between">
    @if(Auth::user()->hasAccess('platform.systems.users'))
        <a href="{{ route('platform.main') }}" class="btn btn-link">
            Админ-панель
        </a>
    @endif
    @if(Auth::user()->hasAccess('word-requests.edit'))
        <a href="{{ route('admin.word-request.index') }}" class="btn btn-link">
            Управление словами
        </a>
    @endif
    @if(Auth::user()->hasAccess('corrections.edit'))
        <a href="{{ route('admin.corrections.index') }}" class="btn btn-link">
            Правки и добавления
        </a>
    @endif
    @if(Auth::user()->hasAccess('questions.edit'))
        <a href="{{ route('admin.questions.index') }}" class="btn btn-link">
            Управление отзывами
        </a>
    @endif
    <form id="logout-form" action="{{ route('platform.logout') }}" method="POST">
        {{ csrf_field() }}
        <button class="btn btn-link">Выход</button>
    </form>
</div>

@yield('content')

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="{{ mix('/js/app.js') }}"></script>
@livewireScripts
@stack('scripts')
</body>
</html>

resources/views/admin/corrections_list.blade.php
@extends('admin.body')

@section('title')Правки и добавления@endsection

@section('content')
    @livewire('admin.corrections-table')
@endsection

@push('styles')
    <style>
        tr.disabled {
            pointer-events: none;
            opacity: .3;
        }
    </style>
@endpush
@push('scripts')
    <script>
        try {
            window.livewire.on('modelSaved', () => {
                $('.btn-close').trigger('click');
                var myModalEl = document.querySelectorAll('#modal_edit_type_0, #modal_edit_type_1');
                myModalEl.forEach(function (el, i) {
                    var modal = bootstrap.Modal.getInstance(el);
                    modal.hide();
                })
            });
        } catch (e) {
            location.reload();
        }
    </script>
@endpush

resources/views/admin/questions_list.blade.php
@extends('admin.body')

@section('title')Управление отзывами@endsection

@section('content')
    @livewire('admin.questions-table')
@endsection

@push('styles')
    <style>
        tr.disabled {
            pointer-events: none;
            opacity: .3;
        }
    </style>
@endpush

@push('scripts')
    <script type="text/javascript">
        try {
            window.livewire.on('modelSaved', () => {
                var myModalEl = document.getElementById('modal_edit');
                var modal = bootstrap.Modal.getInstance(myModalEl);
                modal.hide();
            });
        } catch (e) {
            location.reload();
        }
    </script>
@endpush

resources/views/admin/w-r.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Запросы</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    @livewireStyles
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/jquery-date-range-picker/0.21.1/daterangepicker.min.css">

@livewire('admin.w-r-moderation-component')

<style>
    .bg-www {
        background: #d9dada;
    }
</style>
@livewireScripts
</body>

resources/views/admin/word_request_list.blade.php
@extends('admin.body')

@section('title')Слова@endsection

@section('content')
    @livewire('admin.word-requests-table')
@endsection

@push('styles')
    <style>
        tr.disabled {
            pointer-events: none;
            opacity: .3;
        }
    </style>
@endpush
@push('scripts')
    <script>
        try {
            window.livewire.on('modelSaved', () => {
                var myModalEl = document.getElementById('modal_edit');
                var modal = bootstrap.Modal.getInstance(myModalEl);
                modal.hide();
            });
        } catch (e) {
            location.reload();
        }
    </script>
@endpush